name: scoop-dash-py
services:
  db:
    environment:
      POSTGRES_PASSWORD: scoopdash
    image: postgres:16
    networks:
      default: null
    ports:
    - target: 5432
      published: "5433"
networks:
  default:
    name: scoop-dash-py_default
